/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Shevaag
 */

public class ConsultantSearch extends javax.swing.JFrame {
private String userRole;
    
    public ConsultantSearch(String role) {  
    this.userRole = role;   
    initComponents();  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConsultantName = new javax.swing.JTextField();
        cmbSpecialization = new javax.swing.JComboBox<>();
        btnSearchConsultant = new javax.swing.JButton();
        btnBackConsultant = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultants = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Consultant Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Specialization");

        txtConsultantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultantNameActionPerformed(evt);
            }
        });

        cmbSpecialization.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Neurology", "Pediatrics", "Orthopedics" }));

        btnSearchConsultant.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchConsultant.setText("Search");
        btnSearchConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchConsultantActionPerformed(evt);
            }
        });

        btnBackConsultant.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBackConsultant.setText("Back");
        btnBackConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackConsultantActionPerformed(evt);
            }
        });

        tblConsultants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Consultant Name", "Specialization", "Availability"
            }
        ));
        jScrollPane2.setViewportView(tblConsultants);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBackConsultant)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(btnSearchConsultant)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtConsultantName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConsultantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addComponent(btnSearchConsultant)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBackConsultant)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultantNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultantNameActionPerformed

    private void btnBackConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackConsultantActionPerformed
           if ("Manager".equalsIgnoreCase(userRole)) {  
        new ManagerDashboard().setVisible(true);  
    } else {
        new CashierDashboard().setVisible(true); 
    }
    this.dispose(); 
    // TODO add your handling code here:
    }//GEN-LAST:event_btnBackConsultantActionPerformed


private void searchConsultants() {
    String consultantName = txtConsultantName.getText().trim().toLowerCase(); 
    String specialization = cmbSpecialization.getSelectedItem().toString(); 

    DefaultTableModel model = (DefaultTableModel) tblConsultants.getModel();
    model.setRowCount(0); 

    try (BufferedReader br = new BufferedReader(new FileReader("consultants.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] consultant = line.split(","); 
            if (consultant.length == 3) {
                String name = consultant[0].trim().toLowerCase();
                String spec = consultant[1].trim();

                
                if ((consultantName.isEmpty() || name.contains(consultantName)) && specialization.equals(spec)) {
                    model.addRow(new Object[]{consultant[0], consultant[1], consultant[2]});
                }
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading consultants file!", "File Error", JOptionPane.ERROR_MESSAGE);
    }

    
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No consultants found!", "Search Result", JOptionPane.INFORMATION_MESSAGE);
    }
}


    private void btnSearchConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchConsultantActionPerformed
        searchConsultants();// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchConsultantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultantSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ConsultantSearch("Cashier").setVisible(true); 
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackConsultant;
    private javax.swing.JButton btnSearchConsultant;
    private javax.swing.JComboBox<String> cmbSpecialization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblConsultants;
    private javax.swing.JTextField txtConsultantName;
    // End of variables declaration//GEN-END:variables
}
